### ISSUE TITLE
JS sources seem to be inconsistent with Coffee

### ISSUE THREAD

**Issue by ns3777k** [node-gitlab/node-gitlab#100]
[fn_wrapper](https://github.com/node-gitlab/node-gitlab/blob/master/lib/ApiBaseHTTP.js#L80) - There's an exception throwing inside a callback that cannot be caught in an external try-catch block (only within `process.on('uncaughtException')`), but in Coffee's [fn_wrapper](https://github.com/node-gitlab/node-gitlab/blob/master/src/ApiBaseHTTP.coffee#L38) no exception is thrown. The same thing in [1.4.0](https://github.com/node-gitlab/node-gitlab/blob/v1.4.0/lib/ApiBaseHTTP.js#L80) tag.

Should be rebuilt, huh?

**Comment by moul** [comment]
good catch!

I just pushed the 1.4.1 version with coffee rebuild, can you try again ?

**Comment by ns3777k** [comment]
yep, that works. thanks :+1:
