### ISSUE TITLE
Why throw 400 error directly?

### ISSUE THREAD

**Issue by rawbean** [node-gitlab/node-gitlab#101]
Some time gitlab return 400 error( try to access unauthorised project ), why gitlab-node throw a error directly, this will cause a asynchronies uncaught exception, why not return the error via callback?  

````
 ApiBaseHTTP.prototype.fn_wrapper = function(fn) {
      return (function(_this) {
        return function(err, response, ret) {
          var arity, ref;
          if (err) {
            debug('an error has occured', err);
            if ((400 <= (ref = err.statusCode) && ref <= 499)) {
              throw "Authorisation error. " + err.statusCode + ". Check your key.";
            }
          }
          arity = fn.length;
          switch (arity) {
            case 1:
              return fn(ret);
            case 2:
              return fn(err, ret || JSON.parse(response.body).message);
            case 3:
              return fn(err, response, ret);
          }
        };
````

**Comment by ns3777k** [comment]
check the issue I created yesterday https://github.com/node-gitlab/node-gitlab/issues/100

**Comment by liuweifeng** [comment]
I have the same doubt. If I show a file that is not exist by `gitlab.projects.repository.showFile`, gitlab-node throw a error but not return the error var callback

**Comment by moul** [comment]
I just pushed the 1.4.1 version with coffee rebuild, can you try again ?

**Comment by liuweifeng** [comment]
done, thank you

**Comment by zxqfox** [comment]
@moul Thanks! :+1:

**Comment by rawbean** [comment]
@moul Thanks!
