### ISSUE TITLE
Ability to fetch project by path_with_namespace

### ISSUE THREAD

**Issue by pjpsoares** [node-gitlab/node-gitlab#103]
Gitlab supports finding projects by /projects/{path_with_namespace}. Right now using the project we may try to use seach, but that will give all the project forks also.

**Comment by dave-irvine** [comment]
You should be able to use:

```
gitlab.projects.show('path_with_namespace');
```

Does this not work for you?

**Comment by pjpsoares** [comment]
You're right it works. Thanks a lot. I thought it would only work with the actual id, but I was wrong.
Closing.
