### ISSUE TITLE
Get all projects ambiguous

### ISSUE THREAD

**Issue by hessphil** [node-gitlab/node-gitlab#125]
Wouldn't it be better to use ```GET project/all``` instead of ```GET project``` to query all projekts?

**Comment by geeeeeeeeek** [comment]
I think it's a tradition to have REST apis like this. Use `resources` to get all, and `resources/:res_id` to get individual.

**Comment by hessphil** [comment]
I mean, if you want to list all projects as shown in the example, you will just get all projects you have access to. Wouldn't it be good to provide the functionality to really get all projects ( off course you need admin rights) by using 
```coffeescript
 @get "projects/all", params, cb
```

as described in the [API DOC](http://doc.gitlab.com/ee/api/projects.html#list-all-projects)
