### ISSUE TITLE
It can't work with dependency of slumber@0.10.0.

### ISSUE THREAD

**Issue by frankLife** [node-gitlab/node-gitlab#138]
The same code work with slumber@0.9.0, but not with version of 0.10.0.

**Comment by get-trucked** [comment]
See #136 it has been fixed, @moul would you be able to publish a npm 1.6.1 release that includes #137  as any npm installs are broken currently.

**Comment by moul** [comment]
Done, v1.7.0 released on npm, sorry again for the break
