### ISSUE TITLE
downloadLatestArtifactFile zip file is not valid

### ISSUE THREAD

**Issue by pelallemant** [node-gitlab/node-gitlab#424]
Hi, thanks for having written this package.

**Description**

I didn't find any example using the download features. I was trying to download the last artifact of one of my project from my gitlab.

**Steps to reproduce**

I'm using `gitlab 10.2.0`.

In my code I wrote :

```
api.Jobs.downloadLatestArtifactFile(project.id, "test", "job_test).then((data) => { 
  fs.writeFileSync("archive.zip", data);
})`
```

The type of data is "string", it doesn't seem to be a Buffer type.
The output file is not a valid zip file ...

I was able to download it via curl.

**Expected behaviour**

The zip file should be valid

**Actual behaviour**

The zip file is not valid.

**Possible fixes**

"data" should be a Buffer, or at least there should be a tip in the README.md to indicate how to make it work, if that function works in a specific configuration.

**Comment by exherb** [comment]
same issue here.

**Comment by pelallemant** [comment]
Thanks. 

In general that happens when we use .toString() on a Buffer. 

I think https://github.com/jdalrymple/node-gitlab/blob/master/src/infrastructure/KyRequester.ts#L46 is the problem.

If the response is not application/json, it should not be transformed to text IMO.

**Comment by pelallemant** [comment]
This ? https://github.com/jdalrymple/node-gitlab/commit/881b87b828cc2b3f686d859a926de5df7c663923

**Comment by pelallemant** [comment]
There is no pagination when you are fetching a binary. 

I will check later, the response should be of content-type: `application/octet-stream` or `application/zip`.

It could be an option `{ returnRawBody: true }`. or via check on the content-type of the response.

Plus, It could be nice to return the response directly, there are usefull data in headers sometimes (like the filename I suppose etc..). It could be an option `{ returnResponse: true }`.

**Comment by pelallemant** [comment]
I did some tests:

### 1) artifact doesn't exist (expired), I run this: 

GET https://mygitlab.com/api/v4/projects/$PROJECT_ID/jobs/artifacts/master/download?job=job_test

response headers contains this (copied from postman):

```
Content-Type →application/json
```

response body:

``` 
{
    "message": "404 Not found"
}
```

### 2) Test downloading the artifacts of a specific job where there is a non-expired artifact

GET https://mygitlab.com/api/v4/projects/$PROJECT_ID/jobs/$JOB_ID/artifacts

response headers contains: (handwritten)

```
Content-Type => application/octet-stream
Content-Disposition => attachment; filename="artifacts.zip"; filename*=UTF-8''artifacts.zip
Content-Transfer-Encoding => binary
```

response body is the binary

### Conclusion

So I think you should check if the Content-Type is explicited as application/json to parse it, or to check if it's an application/octet-stream to return directly the Buffer ;)

**Comment by pelallemant** [comment]
I did a minimal test

```
const ky = require('ky-universal').default;
const fs = require('fs');

(async () => {
    try {
      const response = await ky.get('https://mygitlab.com/api/v4/projects/387/jobs/4286/artifacts', {
        headers: {
          'PRIVATE-TOKEN': 'TO_REPLACE'
        }
      });
      
      var blob = await response.blob();
      
      console.log(blob["type"]);
      
      // blob to buffer, using 'Response API' : https://stackoverflow.com/questions/15341912/how-to-go-from-blob-to-arraybuffer
      var buffer = await new Response(blob).buffer();
      fs.writeFileSync("test.zip", buffer);
      
    }
    catch(e) {
      console.log(e);
    }
 
    //=> `{data: '🦄'}`
})();
 
```

You need to use `await` before ` response.blob()`, in order it downloads the whole response body.

Plus the response is a Blob, never seen that, was a pain to figure out how to convert to Buffer ;)

The test worked in local, the downloaded zip is not corrupted :)

**Comment by pelallemant** [comment]
You could replace `return response.blob();` by:

```
var blob = await response.blob();
var buffer = await new Response(blob).buffer();

return Promise.resolve(buffer);
``` 

I think it would do the trick

**Comment by pelallemant** [comment]
I'm trying to use your PR via :

```

**Comment by pelallemant** [comment]
I replaced node_modules/gitlab by your project, checked-out 7d6ac3ff4d589dc3a9c164529a114287ec4f7b31 , `npm i` + `npm run build` .

In my script I used `return api.Jobs.downloadSingleArtifactFile(project.id, 4286, "", false);` 

I receive an object in the then, and using `fs.writeFileSync(path.join(__dirname, "tmp", "archive.zip"), content);` worked :)

Good job !

**Comment by Markus-Ende** [comment]
This is still happening for me, I'm using v11.4.1

**Comment by jdalrymple** [comment]
@Markus-Ende Is it your own gitlab instance? or gitlab.com?

**Comment by jdalrymple** [comment]
Seems like a werid aws things to name it binary/octet-stream. Anyways, I've made the adjustment to the code, next release should be good for you!

**Comment by Markus-Ende** [comment]
@jdalrymple thanks for fixing this so quickly! It is an own instance inside a big company. I'm sorry if it is a self-made issue.. can't check it, though, don't have access to the configuration.

**Comment by jdalrymple** [comment]
@Markus-Ende I don't think its self made!! Probably just a side effect of AWS. No worries, should be good for the future now :)
