### ISSUE TITLE
Cli do not work with self hosted gitlab

### ISSUE THREAD

**Issue by ivanlunardi** [node-gitlab/node-gitlab#458]
**Description**
the command-line do not work on self hosted gitlab,
but if i try with module inside a js project it work

`{ HTTPError: Forbidden
    at fn (/usr/local/lib/node_modules/gitlab/node_modules/ky/umd.js:337:12)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  name: 'HTTPError',
  response:
   Response {
     size: 0,
     timeout: 0,
     [Symbol(Body internals)]: { body: [PassThrough], disturbed: true, error: null },
     [Symbol(Response internals)]:
      { url:
         'https://gitlab.com/api/v4/users?*****************
        status: 403,
        statusText: 'Forbidden',
        headers: [Headers],
        counter: 0 } },
  description: '403 Forbidden  - Not authorized to access /api/v4/users' }`

**Steps to reproduce**

Set the env variable in bash 
export GITLAB_URL=https://*********    or GITLAB_HOST
export GITLAB_TOKEN=aaaaaaaaaaaa

gitlab users all

**Expected behaviour**

get the users list of our gitlab

**Actual behaviour**

the library try to connect to to gitlab.com

**Comment by jdalrymple** [comment]
Ill check it out!!

**Comment by ivanlunardi** [comment]
Thank You!

**Comment by SYip** [comment]
I would like to use it as a gitlab client, however, I find that it does not read the .env located in project directory and environment variable GITLAB_TOKEN in my machine. (MacOSX)

**Comment by jdalrymple** [comment]
@SYip Yea I'm looking into this :)

**Comment by jdalrymple** [comment]
Took a while, but i finally found the problem. Working on fixing it up :)

**Comment by casz** [comment]
@jdalrymple I'd be interesting in the PR if you could point out where the bug was 😓

**Comment by jdalrymple** [comment]
Already have the fix, but still testing different scenarios :P Should have a PR submitted in the next 24 hours.

**Comment by jdalrymple** [comment]
Fixed, give the PR a look over all ill merge it :)
