### ISSUE TITLE
`t is undefined` error thrown in Firefox when importing

### ISSUE THREAD

**Issue by jallbrit** [node-gitlab/node-gitlab#475]
**Description**
I will admit I am a beginner to js/node and it is likely that I am doing something wrong, however I cannot find a solution. I am using the API inside javascript in my website. I installed the package using `npm`, and can successfully link to the package like so:
```
<script src="/node_modules/gitlab/dist/index.browser.js"></script>
```
However, Firefox reports this in the developer javascript console:
```
TypeError: t is undefined                             index.browser.js:1:65052
```

**Steps to reproduce**
1. Run `npm install gitlab`
2. Link to the `index.browser.js` file in an `html` file
3. Check developer console to see error

**Expected behaviour**
It is expected to not see the syntax error.

**Actual behaviour**
The syntax error is thrown and renders the package unusable.

**Possible fixes**
Not sure.

**Comment by jdalrymple** [comment]
hmm, It should work :s. Ill give it a look soon and get back to you!!

**Comment by jallbrit** [comment]
I appreciate the quick fix, that error went away! However, I'm greeted with yet another error unfortunately...
```
ReferenceError: require is not defined                        index.browser.js:1:76503
```

**Comment by jdalrymple** [comment]
Looking into it. @DanielRuf Thoughts?

**Comment by DanielRuf** [comment]
Not sure. This should be handled by the https://github.com/rollup/rollup-plugin-node-resolve plugin.

Not sure, I did no further testing and I am not a rollup user in general.

**Comment by jdalrymple** [comment]
Alrighty, ill try and get around to it @jallbrit sorry for the delay :(

**Comment by jallbrit** [comment]
@jdalrymple all is good! My other question is, with the exception of the CLI tool, is there some other way to use this package than importing the API into a browser and using js? These problems seem like they would affect all users of this package.

**Comment by jdalrymple** [comment]
You could use it in plain nodejs, which does have access to the underlying libraries that where causing this problem. That's probably why it wasn't noticed.
