### ISSUE TITLE
api.Projects.all() never resolves

### ISSUE THREAD

**Issue by iOSt0p** [node-gitlab/node-gitlab#484]
**Description**

Trying to get a list of my repos from Gitlab CE.
`await api.Project.all()` never resolves.
Account has exactly 1 repo.

Token scopes: `api, read_repository, write_repository`

```
//token is fake
const api = new Gitlab({
  token: 'KNusRmV8Fnp_s4AKV8Ax'
});
```

logging api.Projects
```
t {
  url: 'https://gitlab.com/api/v4/',
  headers: { 'private-token': 'KNusRmV8Fnp_s4AKV8Ax' },
  rejectUnauthorized: true,
  camelize: false,
  requester:
   { get: [Function],
     post: [Function],
     put: [Function],
     delete: [Function],
     stream: [Function] },
  requestTimeout: 300000 }
```

**Steps to reproduce**

- Await api.Projects.all()

**Expected behaviour**
Returns a list of account's repos.

**Actual behaviour**
Never resolves.

**Comment by casz** [comment]
Well you say gitlab-ce so I assume you mean your own gitlab instance.
I wonder why your not setting a gitlab host than :)

```
const api = new Gitlab({
  token: 'KNusRmV8Fnp_s4AKV8Ax'
  host: 'https://gitlab.company.com'
});
```

Otherwise `api.Projects.all()` is trying to resolve against github.com and that could take a while 😆

**Comment by iOSt0p** [comment]
By gitlab-ce I meant gitlab.com

Anyway I might not have waited enought, thanks :)
