### ISSUE TITLE
Missing index.d.ts file as of 11.3.2

### ISSUE THREAD

**Issue by gwardwell** [node-gitlab/node-gitlab#485]
**Description**

I began encountering the following error when building my typescript application after upgrading from version 11.3.1, which was my last installed version, to version 11.4.0:

```
Could not find a declaration file for module 'gitlab'. '/Users/REDACTED/node_modules/gitlab/dist/index.js' implicitly has an 'any' type.
  Try `npm install @types/gitlab` if it exists or add a new declaration (.d.ts) file containing `declare module 'gitlab';`

1 import { Gitlab, ProjectId, IssueId } from 'gitlab';
```

I narrowed the issue down to the fact that `node_modules/gitlab/package.json` has the `"types": "dist/index.d.ts",` field, but `dist/index.d.ts` no longer exists. I also isolated the problem to the `v11.3.2` release (which I had skipped).

**Steps to reproduce**

Prep: create a file that includes the gitlab package. Something as simple as this:

```ts
// index.ts
import { Gitlab } from 'gitlab`
```

- run `npm i gitlab@11.3.1`
- run `tsc`
- it should build with no errors
- run `npm i gitlab@11.3.1 --latest`
- run `tsc`
- you should see a similar error to the one I mentioned above

**Expected behaviour**

There should be no errors related to gitlab typings when running `tsc` on my project

**Actual behaviour**

There are typing errors.

**Possible fixes**

Make sure the `dist/index.d.ts` file is being properly generated again.

**Comment by Markus-Ende** [comment]
Same problem in v11.4.0.

**Comment by gwardwell** [comment]
Yep, I noticed it in 11.4.0, confirmed that it was also in 11.3.2, and found that rolling back to 11.3.1 solved my problem.

**Comment by jdalrymple** [comment]
kinda surprised the error isnt there from 11.3.1 since the dist/index.d.ts file still dne. Anyways should be good for the next release :)
