### ISSUE TITLE
downloadLatestArtifactFile zip file is not valid 

### ISSUE THREAD

**Issue by Markus-Ende** [node-gitlab/node-gitlab#488]
**Description**
This is a re-opening of issue #424. 

Same error, returned data is of type String instead of Buffer.

**Steps to reproduce**

See #424

**Possible fixes**

Problem in my case is, that gitlab returns content-type `binary/octet-stream`, but `KyRequester` only checks for `application/octet-stream`: 

[Line 51 in KyRequester.ts](https://github.com/node-gitlab/node-gitlab/blob/77050869288fec18f0e7b4545c3fbad50e442f90/src/core/infrastructure/KyRequester.ts#L51)

**Comment by jdalrymple** [comment]
Going to close this and reopen the last one. Ill look into it :) Thank you!!
