### ISSUE TITLE
Help understanding the API

### ISSUE THREAD

**Issue by jallbrit** [node-gitlab/node-gitlab#489]
I want to use this API to query on GitLab users, given their username. For example, using plain `curl`, it's this easy:
```
curl "https://gitlab.com/api/v4/users?username=jallbrit"
```
A parse-able `json` is returned containing the information I want.

However, I cannot figure out how to accomplish this given this js API. I can see in the documentation how to initiate the GitLab instance, and a couple examples are given:

```
let projects = await api.Projects.all({ maxPages: 2 });
```
or
```
api.Projects.all().then(projects => {
  console.log(projects);
});
```
However, I don't understand what `api.Projects.all()` is supposed to represent. I know that to use the `users` API, I start with `api.Users`, but I don't understand what comes after. For example, what functions are available under `api.Users` other than `all()`? And what arguments does `all()` take?

Perhaps additional examples in the documentation, or links to resources could help me understand. Thank you!

Edit: by pure trial and error, I have determined that `api.Users.all({ username: "jallbrit" })` returns the results I'm looking for. But my questions remain: what other functions are available, and why is it that `api.Users.all()` accomplishes this?

**Comment by jdalrymple** [comment]
Hey @jallbrit!! Documentation is definitely the next big step for this library #360 , unfortunately it takes a lot more time that I currently don't have while still fixing bugs etc :(. I'm glad you found what you were looking for though! The easiest way in the future is simply looking at the source. Its pretty well laid out to find what you're looking for which could save a bit of time. 

As as to your question, why `all`? Well its a two part thing. One, it was the API that was used initially when I refactored this project. I didn't want to modify it to much for those who were using the old one and those who wanted to adopt this updated version. Secondly, its pretty intuitive. When I want a list of all the projects, it would rightly be Projects.all(), and the same naming convention holds for every API in the library** (there are a couple exceptions lol). Yes we could of gone with other words like `list`, but alas we didn't lol.

**Comment by casz** [comment]
@jallbrit This is how you use the API for finding users:

```javascript
const users = api.Users.search("jallbrit")
users[0]
```
Search always returns an array.

Depending on the amount of users you have in your gitlab instance it might be quicker to just get all users and use javascript's `find` method to locate them :)

```javascript
const users = api.Users.all();
const jallbrit = users.find(user => user.username === "jallbrit");
```

**Comment by jallbrit** [comment]
@casz Thank you. How did you know that `.search()` is available- how could I have found that?

**Comment by casz** [comment]
either by using typescript, it should tell what methods do exist or looking into the code 😅

**Comment by jallbrit** [comment]
@casz thank you for that reference, it's very helpful! However, I've hit a road block. When i run 
```
let user = await api.Users.all({
  username: <username>
});
```
The query is the same as running
```
curl "https://gitlab.com/api/v4/username=<username>"
```
As such, the results are limited- only username, id, avatar_url, web_url, state, and name are listed. I want to get more info, like bio, twitter, website_url, etc. The proper way to get that extra information is like this:
```
curl "https://gitlab.com/api/v4/users/<id>"
```
But I cannot find the equivalent via this API. Running:
```
let user = await api.Users.all({
  id: <id>
});
```
does not work because it is the equivalent of running:
```
curl "https://gitlab.com/api/v4/id=<id>"
```
which is different (and doesn't work anyways). Any ideas?

**Comment by casz** [comment]
@jallbrit again the method you want here is `api.users.show(5)`

```
https://github.com/node-gitlab/node-gitlab/blob/f6dcbd796a301deebd70468dfc135c14b21c8022/src/core/services/Users.ts#L59-L63
```
