### ISSUE TITLE
Add support for MergeRequestApprovals

### ISSUE THREAD

**Issue by LRH539** [node-gitlab/node-gitlab#496]
**Description**
I've noticed that there's currently no support for merge request approvals. This API endpoint has been available since GitLab 10.6: https://docs.gitlab.com/ee/api/merge_request_approvals.html

**Proposal**
I suggest to support his API endpoint, the implementation should be straightforward and similar to other endpoints.

**Comment by shobull** [comment]
It is already supported: https://github.com/node-gitlab/node-gitlab/blob/40546d5d534fd65b592d787c948ac66cceab569f/src/core/services/MergeRequests.ts#L131

usage is `MergeRequests.approvals(projectId, {})`

**Comment by jdalrymple** [comment]
I really should remove the need for the empty {} :thinking:
