### ISSUE TITLE
I can't get normal results from your sdk.

### ISSUE THREAD

**Issue by liwen-tj** [node-gitlab/node-gitlab#498]
Here is an example.
```
const { Gitlab } = require('gitlab');
const gitlab = new Gitlab({
  host: 'host-address',
  token: 'my-personal-token',
});

console.log(gitlab.Projects);
```
I find it always get **rejectUnauthorized=true**. 

Instead, when I try this command `curl --header "PRIVATE-TOKEN: my-personal-token" host-address/api/v4/projects`, I get the right result.

What is the problem?

**Comment by jdalrymple** [comment]
Might be related to #357

**Comment by liwen-tj** [comment]
I still don't understand how to solve my problem. 
Can you give me some examples that can return normal results? I am just starting to use your sdk.
Many thanks in advance !!

**Comment by liwen-tj** [comment]
Is there any difference for params between http and https. I find your example use http. But mine uses https.

**Comment by jdalrymple** [comment]
There is no difference in params. What exactly is your problem? It sounds like youre trying to access a host without the correct certificate. This is exactly what is brought up in #357 but i havent gotten around to fixing the small issue. The only solution would be adding the certificate to your pc. See: https://github.com/node-gitlab/node-gitlab#handling-https-certificates

**Comment by liwen-tj** [comment]
I have solved my problem by replacing 
`console.log(gitlab.Projects);` 
with
```
gitlab.Projects.all().then(projects => {
  console.log(projects);
});
```
