### ISSUE TITLE
All apis get with namespace/project instead of project_id not working

### ISSUE THREAD

**Issue by jeffreyliim** [node-gitlab/node-gitlab#503]
All the apis doesn't support get with namespace/project, only supports get with project id. Can fix be done soon?

**Comment by casz** [comment]
Depending on which APIs your referring to, it might be a limitation on gitlab's api or it could be bug in the nodejs implementation.

But more details as to which method call you have in mind would help.

**Comment by jeffreyliim** [comment]
@casz I think its a limitation on gitlab's node sdk that doesn't support namespace with project path. It works on regular http calls but not working on sdk. 

I've tried several APIs i.e. getting a single project by project id

**Comment by casz** [comment]
Could you please specify which APIs as I haven't experienced this issue.

**Comment by casz** [comment]
Could you share some code snippets with the project names you tried?
Are these by any chance Chinese characters and are you sure those are UTF-8 encoded?

**Comment by jeffreyliim** [comment]
```javascript
async FindPipeline(project_id, pipeline_id) {
        if (typeof project_id !== 'number') {
            project_id = project_id.split('/').join('%2F');
        }
        return await generalHttpWrapper(
            `https://gitlab.${process.env.GITLAB_HOST && process.env.GITLAB_HOST + '.' || ''}com/api/v4/projects/${project_id}/pipelines/${pipeline_id}`,
            'GET',
            null,
            {"private-token": process.env.GITLAB_TOKEN},
            'FindPipeline'
        )
    }
```


```javascript
constructor() {
        let config = {
            token: process.env.GITLAB_TOKEN,
        };
        if (process.env.GITLAB_HOST) {
            config['host'] = process.env.GITLAB_HOST
        }
        this.api = new Gitlab(config);
        console.log('Gitlab client initialized')
    }

async FindPipeline(project_id, pipeline_id) {
        if (typeof project_id !== 'number') {
            project_id = project_id.split('/').join('%2F');
        }
       
         return await this.api.Pipelines.show(project_id, pipeline_id).then(response => {
             return successResponse(response)
         }).catch(error => {
             return gitlabErrorResponse(error, 'FindPipeline')
         })
    }
```



The above works but not the below one

**Comment by casz** [comment]
you shouldn't mess with the project id. We will handle encoding for you.

**Comment by jdalrymple** [comment]
@casz Yea for sure! @jeffreyliim, does removing the encoding in your code solve the problem? Specifically changing it to:

```javascript
async FindPipeline(project_id, pipeline_id) {
        return await this.api.Pipelines.show(project_id, pipeline_id).then(response => {
             return successResponse(response)
         }).catch(error => {
             return gitlabErrorResponse(error, 'FindPipeline')
         })
    }
```

Also as a side note you could remove your first promise handler and just pass the function to the then like:

```
async FindPipeline(project_id, pipeline_id) {
...
         return await this.api.Pipelines.show(project_id, pipeline_id)
         .then(successResponse)
         .catch(error => {
             return gitlabErrorResponse(error, 'FindPipeline')
         })
    }
```

**Comment by jeffreyliim** [comment]
Thanks for assisting. It now works fine

**Comment by ccoenen** [comment]
A note for future search-engine visitors of this issue:

This library absolutely supports `namespace/path` lookup. In my case that didn't work, though, because I use Apache as a frontend ReverseProxy. In that case, any `%2f` will be interpreted as an invalid URL.

These two things will prevent that:
`AllowEncodedSlashes NoDecode`
`ProxyPass (... whatever you have configured here ...) nocanon` - the `nocanon` is the kicker, here.

Also see https://stackoverflow.com/a/9933890/2413043 for more info.
