### ISSUE TITLE
Add support for all inherited members endpoint (ancestor groups) - /groups/:id/members/all/:user_id

### ISSUE THREAD

**Issue by MadLittleMods** [node-gitlab/node-gitlab#507]
Add support for the following endpoints as documented in https://docs.gitlab.com/ee/api/members.html#get-a-member-of-a-group-or-project-including-inherited-members

 - **`GET /groups/:id/members/all/:user_id`**
 - **`GET /projects/:id/members/all/:user_id`**

This endpoint is special because it "includ[es] members inherited through ancestor groups."

We are using this in Gitter to support GitLab based communities/rooms, https://gitlab.com/gitlab-org/gitter/webapp/merge_requests/1679

---

Normal endpoints which don't include inherited ancestor group members (these are already supported), https://docs.gitlab.com/ee/api/members.html#get-a-member-of-a-group-or-project

```
GET /groups/:id/members/:user_id
GET /projects/:id/members/:user_id
```

**Comment by casz** [comment]
this is already supported.
https://github.com/node-gitlab/node-gitlab/blob/63b11574aa1db3b88be3b3baeb16dbaceb9e566b/src/core/templates/ResourceMembers.ts#L17

set `includeInherited` to true

**Comment by casz** [comment]
ah, this was introduced in `GitLab 12.4.` as note by https://docs.gitlab.com/ee/api/members.html#get-a-member-of-a-group-or-project-including-inherited-members

So obviously this is currently not supported 😓

**Comment by casz** [comment]
btw I love the fact that Gitlab/gitter is using this library 🥰

**Comment by MadLittleMods** [comment]
@jdalrymple @casz I got this [working and all integrated](https://gitlab.com/gitlab-org/gitter/webapp/merge_requests/1679) now 🚀 Thanks for the great support and quick update  ❤️

**Comment by jdalrymple** [comment]
@casz Next step is to clean it up a bit #483 ;)
