### ISSUE TITLE
401 Unauthorized error

### ISSUE THREAD

**Issue by osmanraifgunes** [node-gitlab/node-gitlab#509]
I use webflow oauth token generation process. My token is coming as a respnse and I send this code to gitlab moudule.
```
const { Gitlab } = require('gitlab');
 const api = new Gitlab({
                            token: JSON.parse(result.body).access_token
                        });

 api.Projects.all().then(function (data) { debugger });
```
Response is =>

```
description:"401 Unauthorized"
message:"Unauthorized"
name:"HTTPError"
response:Response {size: 0, timeout: 300000, Symbol(Body internals): Object, …}
stack:"HTTPError: Unauthorized\n    at fn (C:\code\RoboticApi\RestApi\node_modules\ky\umd.js:279:12)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at async Ky._retry (C:\code\RoboticApi\RestApi\node_modules\ky\umd.js:352:12)"
__proto__:Error {constructor: }
```

**Comment by jdalrymple** [comment]
If its an oauth token, it must use the 'oauthToken' option in the constructor. The 'token' option is for personalTokens. :)

**Comment by osmanraifgunes** [comment]
Then it gives : 

HTTPError: Internal Server Error
description:"500 Internal Server Error"
message:"Internal Server Error"
name:"HTTPError"
response:Response {size: 0, timeout: 300000, Symbol(Body internals): Object, …}
stack:"HTTPError: Internal Server Error\n    at fn (C:\code\RoboticApi\RestApi\node_modules\ky\umd.js:279:12)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at async Ky._retry (C:\code\RoboticApi\RestApi\node_modules\ky\umd.js:352:12)"
__proto__:Error {constructor: }

**Comment by osmanraifgunes** [comment]
This worked for me : 

   ```
const api = new Gitlab({
                            oauthToken: JSON.parse(result.body).access_token
                        });
                        api.Users.current().then(function (data) {
                                debugger;
                                api.Users.projects(data.id).then(function (data) {
                                debugger;
                            });
                        });
```

thanks.

**Comment by jdalrymple** [comment]
Seems odd, since their are tests for Project.all and they are passing. Perhaps it has to do with the amount of projects being returned for the .all function. Perhaps set a maxPages option?

**Comment by casz** [comment]
if you run against gitlab you gotta be very careful with `api.Projects.all()` :)

**Comment by jdalrymple** [comment]
Closed for now, if you get any more information ill reopen :)
