### ISSUE TITLE
how do I enable debugging?

### ISSUE THREAD

**Issue by meonkeys** [node-gitlab/node-gitlab#66]
I noticed that the `debug` package is used by this node module. Can I enable debugging from my own Node.js code while I'm using this module? If so, how?

**Comment by moul** [comment]
You can find the whole documentation on the official repo: https://github.com/visionmedia/debug

I personally don't enable debug from the code, I prefer to set the environment variable DEBUG when calling the process, i.e.:

    DEBUG='*' node app.js
    # or only gitlab debug
    DEBUG='gitlab:*' node app.js

There is probably a way to enable debug from the code, maybe something like

    process.env['DEBUG'] = '*'

**Comment by meonkeys** [comment]
Thank you! I tried a few things (including setting the env var `DEBUG='gitlab'`, without the star), but what you provided works perfectly.
