### ISSUE TITLE
I made git history a mess

### ISSUE THREAD

**Issue by dave-irvine** [node-gitlab/node-gitlab#78]
With https://github.com/node-gitlab/node-gitlab/commit/0a1e5b4cc9471feb1bb3357d27b2abb0dc95f88e I performed a merge commit rather than rebasing first. Now we have a messy git history.

Ideally I would reset to the last good commit https://github.com/node-gitlab/node-gitlab/commit/4ebbde804f6bd1b1cbda6605465c05361f567554 and do a force push but that can be bad in collaborative environment.

@moul How much do we care about clean git history? Worth a force push to clean up?

**Comment by moul** [comment]
I don't care much about git history beauty in our case, but since the commit is very "young", do not hesitate to `git rebase && git push -f` :)

**Comment by zxqfox** [comment]
But please try to avoid that in master ;-)

**Comment by moul** [comment]
@zxqfox yes sure, thank you :)
