### ISSUE TITLE
Example list-users and others only lists first page

### ISSUE THREAD

**Issue by kaizers** [node-gitlab/node-gitlab#84]
Can we setup examples that lists all users, groups, repos, etc.

**Comment by EricRohlfs** [comment]
I have the same question.  I want to see ALL projects.  If I understand correctly Gitlab has a max of 100 items per call.  Then there are two options, look at the headers for the next page, or just increment the page number and keep going till there are no more results returned.  Doing this fragmented work async is not always suitable for specific use cases.  I have not used this library but looking through the code I did not see an example of how this aggregation is taking place.  I apologize in advance if this api solves the pagination issue and I did not see it.

**Comment by dave-irvine** [comment]
Resolved in #98

**Comment by eddiemonge** [comment]
This is only for users and groups. How do we do this for all resources?

**Comment by dave-irvine** [comment]
@eddiemonge as in, you would like examples for all the resource types we support?

**Comment by eddiemonge** [comment]
As in, how do I get all merge requests and not just the first 100? How do I tell how many in total there are? Doesn't seem like this is setup for pagination at all.
