### ISSUE TITLE
Project search endpoint?

### ISSUE THREAD

**Issue by jonascript** [node-gitlab/node-gitlab#87]
Hello,
Is there a command that wraps this endpoint to do search? I can't seem to find one in the source...

GET /projects/search/:query

**Comment by stevenorman** [comment]
I've added it on my own fork, change I made was to src/Models/Projects.coffee

+  search: (projectName, params={}, fn=null) =>
+    if 'function' is typeof params
+      fn = params
+      params={}
+
+    @debug "Projects::search()"
+    @get "projects/search/#{projectName}", params, (data) => fn data if fn
+

The commit https://github.com/stevenorman/node-gitlab/commit/b7f6769d1144104decf5bae40ed0f164dde66ecd also adds remove functionality for a project.

**Comment by dave-irvine** [comment]
Fixed in #93
