### ISSUE TITLE
Use headers instead of query string for private token

### ISSUE THREAD

**Issue by stevenorman** [node-gitlab/node-gitlab#91]
At the moment the code is passing the private token on the querystring which means that it can be logged into any number of log files (proxy server or the final web server).   Gitlab itself does filter out the string in its own logs but I was seeing the private token in nginx logs which probably isn't a good thing.

I think it is a simple 1 line fix in the code and a move to a newer version of slumber (0.6 minimum, but I've been testing on 0.7 so far).

I would raise a merge request but my fork has a few other commits on the develop branch so that would confuse things.   The commit I made is at https://github.com/stevenorman/node-gitlab/commit/0b55895d22caf8a4ac1415dfce6095d4bdd119a6

Change is in ApiBaseHTTP.coffee:

   prepare_opts: (opts) =>
     opts.__query ?= {}
-    opts.__query.private_token = @options.token
+    opts.headers = { 'PRIVATE-TOKEN': @options.token }
     return opts

**Comment by dave-irvine** [comment]
LGTM, as long as @moul is happy to depend on slumber > 0.6

**Comment by moul** [comment]
yes :+1: !

**Comment by stevenorman** [comment]
Closing as this has been merged in.
