### ISSUE TITLE
Exceptions are thrown winthin callback - cannot be caught

### ISSUE THREAD

**Issue by it-ony** [node-gitlab/node-gitlab#95]
Exceptions can be thrown and caught with a try-catch-block for synchronous call. For asynchronous methods, that except a callback, errors must not be thrown, but returned as first parameter of the callback. See http://stackoverflow.com/questions/7310521/node-js-best-practice-exception-handling.

The ApiBaseHTTP.js file throws an exception from a callback which cannot be detected. https://github.com/node-gitlab/node-gitlab/blob/develop/lib/ApiBaseHTTP.js#L77-79

Here is a simple example
```
try {
    gitlab.projects.repository.showFile(1, {
        ref: "master",
        file_path: "nonExistingFile"
    }, function(file, err) {
        console.log(arguments);
        // callback won't be invoked
    });
} catch (e) {
    // exception cannot be caught here
} 
```

The only way to detect the exception is 

```
process.on('uncaughtException', function(err) {
    logger.fatal(err);
});
```  

but, here the scope of e.g. a request/response function is not available.

**All asynchronous errors must be passed to a callback instead of being thrown**,  otherwise the library is kind of not usable.

**Comment by dave-irvine** [comment]
This is fixed in develop.

https://github.com/node-gitlab/node-gitlab/blob/develop/src/ApiBaseHTTP.coffee#L38
